ArkEcosystem/mobile-wallet

- src/pages/contacts/contact-list/contact-list.ts
In relation to #5.
Noticed that we used addresses as the keys, but then when we called load it would use the name as the key instead, which would mess everything up since then address would be 'key' which would just be a name. 
I've tested it, adding contacts, editing, and deleting should work now.
> Fix contacts editing/deleting/adding issues 

- src/app/app.constants.ts
- src/pages/delegates/delegates.ts
- src/providers/ark-api/ark-api.ts
Zillion made a good point (#8), we should limit the number of delegates that need to be gotten/loaded, since plenty of the standby delegates aren't close to being active.
Generalized fetchAllDelegates to fetchDelegates which takes in two parameters.
First is a boolean which is called getAllDelegates if true -> will get all the delegates.
Second is the number of delegates you want, if getAllDelegates is false then we use this to get the totalPages. 
Did this instead of having two methods, fetchDelegates and fetchAllDelegates, seemed cleaner. 
For the pr I have every fetchDelegates call set to false and 102, so 51 active delegates + next 51 for standby.
Open to suggestions!
> Limit number of delegates fetched

- package.json
- src/pages/transaction/transaction-send/transaction-send.ts
Relates to #35 
Fixes rounding issue where amount has a decimal within the transaction itself, when that should never be the case. E.g. Incorrect decimal value `{"amount":8259999999.999999` instead of `8260000000`
> Use BigNumber for determining amount

- src/pages/settings/settings.ts
- src/pages/transaction/transaction-show/transaction-show.ts
This PR makes two changes to opening links in the app by adding a '_system' parameter, and solves issue #34 :
* Transactions -> Open in explorer: this will now open in the browser defined by the user, instead of the in-app webview
* Privacy Policy: I have changed this to open in the browser too, but I am not sure if this is necessary. Would love to hear a response from any of you regarding this. My preference goes out to the browser, as I don't like the in-app browser version myself. However, I see how opening the browser for a .txt file can be cumbersome to some and would prefer to simply view it in the app.
> Open external links in browser

- src/pages/contacts/contact-create/contact-create.ts
When trying to add a new contact, the QR code scanner did not save the address (and did not show an error either). This PR solves that issue and also adds an error message in case the QR did not contain a valid address.
> Enable scanning QR code when adding new contact

- src/assets/i18n/en.json
- src/components/confirm-transaction/confirm-transaction.ts
- src/modals/confirm-transaction/confirm-transaction.html
- src/modals/confirm-transaction/confirm-transaction.scss
- src/models/contact.ts
- src/models/model.ts
- src/models/translate.ts
- src/pages/contacts/contact-create/contact-create.ts
- src/pages/transaction/transaction-send/transaction-send.html
- src/pages/transaction/transaction-send/transaction-send.scss
- src/pages/transaction/transaction-send/transaction-send.ts
- src/pipes/units-satoshi/units-satoshi.ts
- src/providers/ark-api/ark-api.ts
- src/providers/auto-complete/contacts-service.ts
- src/providers/toast/toast.ts
- src/utils/ark-utility.ts
Noticed multiple bugs in the send transaction form concerning the contact:
- if you selected an existing contact and clicked into the same field again, the new contact field did appear
- "Contact" was hardcoded in english
- the `recipientName` was not always set
I fixed this, refactored and also changed the following:
- changed sort orer to the following:
- all contacts (alphabetical)
- all wallets
- labeled wallets (alphabetical)
- unlabled wallets (alphabetical)
- added icons for contacts and wallets and show the address to the contact / label on the second line:
- searched words are highlighted within the results:
- logic of when the "new contact" field appears:
- if you type an address
- if you scan a qr code and there is NO corresponding contact or wallet
- if you select a wallet …
> Fix address/contacts bug in send-transaction & more

- src/assets/i18n/en.json
- src/directives/mainnet-only/mainnet-only.ts
- src/modals/passphrase-word-tester/passphrase-word-tester.html
- src/modals/passphrase-word-tester/passphrase-word-tester.module.ts
- src/modals/passphrase-word-tester/passphrase-word-tester.scss
- src/modals/passphrase-word-tester/passphrase-word-tester.ts
- src/modals/wallet-backup/wallet-backup.module.ts
- src/modals/wallet-backup/wallet-backup.ts
- src/models/model.ts
- src/models/passphrase-word.ts
- src/providers/user-data/user-data.ts
- src/utils/ark-utility.ts
I always liked the word validation which we have in ark-desktop, so I added the same validation here.
A few notes:
- I designed the word validation so that it will also work with a different nubmer of words, or more words, etc. => we could also make it random, each time a passphrase is generated (so the user cannot simply remember the 3, 6 and 9 word)
- I added a little gimmick, that when we are on `devnet` the words area already prefilled, so we can go faster in testing (for this purpose I added a gett er `isTestNet` to the `UserDataProvider` so we could also use this feature elsewhere (if you approve it of course ;) )
By the way if you omitted this feature on purpose on mobile, you can of course decline the PR, I really just wanted to play a little with cordova and get into it and find …
> Add word validation when generating passphrase

- src/modals/pin-code/pin-code.ts
Resolves #47 by updating the pin inside of ngZone so that angular can see the change and update the pin dots.
Looks like this was removed [here](https://github.com/ArkEcosystem/ark-mobile/commit/61878255a6544164dc58af2528604432771b8460#diff-8fe260f49b456b3de01f92aecd299ee4L49) in an attempt to reduce the input lag when entering your pin, but I think the real solution was added in PR #24.
> Fix pin dots not updating when creating wallet

- .travis.yml
- missing-translations.js
- package.json
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/pages/transaction/transaction-receive/transaction-receive.html
- src/pages/transaction/transaction-receive/transaction-receive.ts
This fixes some translations in german.
Please note:
Whenever possible we should **inlcude** parameters in the translation text, and not just "append" them, because in other languages (i.e. in this case in german) the word is not in the same place
I also realized it's hard to find out which translations are actually missing.
I googled if `ngx` offers anythign concering that, unfortunately I couldn't find something.
So I wrote a small script, which displays all missing translations keys on the console.
I added this to travis. Maybe later we can publish the results to some file or something like that, so that it can be easily picked up.
The result looks like this:
```
Missing translations in gr.json (7):
API.BALANCE_TOO_LOW_DETAIL
API.DESTINATION_ADDRESS_ERROR
PASSPHRASE_TEST …
```
> Improve german translations & add script to find missing translations

- src/assets/i18n/de.json
- src/components/pin-code/pin-code.ts
- src/modals/pin-code/pin-code.ts
- src/providers/auth/auth.ts
- fix race condition in increasing attempts
- problem was, that the "storage.set" method is async and therefore was not always done, when the next call to increasedAttempts was made, therefore sometimes an old value was returned.
- This resulted in the problem, that you still had infinite tries to "brute-force" the pin
-  don't show error when pin code dialog is closed (when signing in)
- german translations updated :>
Hope my `mergeMap` usage is correct, always find this hard!
Probably a PR for @luciorubeens since you implemented that attempt-stuff.
> 2 bug fixes & translation update

- src/assets/i18n/en.json
- src/assets/i18n/nl.json
- src/pages/wallet/wallet-import/wallet-import.html
In the 'Import wallet' screen, part of the 'or type secret passphrase' sentence was not being translated
> Added phrase that was not yet translated

- src/models/settings.ts
- src/pages/intro/intro.ts
- src/providers/settings-data/settings-data.ts
When starting the app for the first time, you'll see a short introduction. This introduction was not properly translated when you set a different language, as the translationService still returned the English values. I've deferred the retrieval of the translations by waiting for the platform.ready() call, but I am not sure whether this is the right way to go. If there is a better way to wait for a translation to be set in Ionic, then let me know!
If you want to review this issue, you can do so as follows:
1) In `app/app.components.ts`, set a different language than 'en' (e.g. 'nl'):
`this.translateService.use('nl'); // Set your language here`
2) Reinstall the app so you'll see the introduction again. The introduction slides will be in English, while the buttons will be translated into the …
> Use user's locale as default app language

- src/providers/settings-data/settings-data.ts
Translations were broken after commit https://github.com/ArkEcosystem/ark-mobile/commit/42aaec81de22d6c959b68e291b8161ba42357a1e, due to the following:
`const appLang = this.AVALIABLE_OPTIONS.languages[cultureLang] || this.AVALIABLE_OPTIONS.languages[browserLang] || 'en';`
This works in case the option list does not contain `cultureLang` or `browserLang`, as it will default to 'en'. However, if it does contain `cultureLang` or `browserLang`, the selected value in `appLang` will be incorrect as the value of the option is taken (while the key corresponds to the actual language file). To give a more concrete example:
Let's say that we have our mobile device set to Dutch. Culturelang will return `nl-NL`, which is not available in the list of options, and browserlang will be `nl`. As a result, …
> Fix issue with user locale not using correct key

- src/app/app.component.ts
- src/pages/transaction/transaction-send/transaction-send.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/pipes/account-label/account-label.ts
- src/providers/ark-api/ark-api.ts
- src/providers/contacts-auto-complete/contacts-auto-complete.ts
- src/providers/user-data/user-data.ts
- fixes delegate not set on wallet when importing wallets (when delegate not in top 102)
- fixes delegate not set on wallet when registering for new delegate
- don't show "Create label" action when wallet is a delegate (because we display the username then)
- introduce getWalletLabel method and use everywhere (unified label display)
- fix "new contact" bugs in send form, problems we had:
- wallet addresses were not recognized / resolved to labels
- sometimes when you clicked in the field, the contact field appeared even though it shouldn't
> Fix mutiple bugs concerning wallets

- src/modals/enter-second-passphrase/enter-second-passphrase.html
- src/pages/transaction/transaction-send/transaction-send.ts
If the wallet has a 2nd passphrase registered, it will now ask for this before sending the transaction instead of simply failing. Fixes #71 
This was actually easier to solve than I had expected 😛
> Enabled 2nd passphrase modal when sending transaction

- src/pages/profiles/profile-create/profile-create.html
When creating a profile, the app would throw a runtime error when the keyboard came up to fill in a name. This is now fixed by adding a proper keyboard attach option.
> Fix runtime error on profile creation page

- src/app/app.component.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.html
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/pages/wallet/wallet-list/wallet-list.html
- src/providers/user-data/user-data.ts
- use accountLabel pipe consistently (don't user label if wallet is a delegate)
Note:
I wrote the `ensureWalletDelegateProperties` so that the wallet is only saved when the delegate state actually changed, i.e. you became a delegate.
Also what's different now is, that the wallet can actually be saved after a "walletRefresh" (method is called) happens, before we never saved it - hope that's not a problem.
> Update wallet delegate status on refresh

- src/modals/confirm-transaction/confirm-transaction.html
- src/modals/confirm-transaction/confirm-transaction.scss
- src/pages/transaction/transaction-show/transaction-show.html
- src/pages/transaction/transaction-show/transaction-show.scss
This is related to https://github.com/ArkEcosystem/ark-mobile/pull/76.
On the send confirmation modal and the transaction details page:
Previous | Now, transaction details | Now, send confirmation
------------ | -----------------------------------| --------------------------------
@luciorubeens any other similar change or a different style?
> Highlight the label of the accounts

- src/pages/transaction/transaction-response/transaction-response.ts
Small change, but the "open in explorer" link on the transaction page still used the in-app browser.
> Show in explorer now makes use of external browser on transaction screen

- src/modals/confirm-transaction/confirm-transaction.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/pages/wallet/wallet-list/wallet-list.ts
- src/providers/market-data/market-data.ts
To be honest, I'm not exactly sure, why the prices were not updated for @zillionn . It's possible that it was a timing problem (e.g. too late subscription to the update of the prices or something like that).
However I found the fetching of the prices & the history wasn't done entirely correctly / optimal anyway.
The problem was, that it could happen that we made too many calls to the API and to our local subscription methods.
I changed the process to something like this:
1. Try get the data from the cache (and ONLY from the cache )
2. If we have data in the cache, display this data immediately
3. Subscribe for future changes in the data
4. Fetch the up-to-date data from the api
Codewise this looks like [this](https://github.com/ArkEcosystem/ark-mobile/compare/master...Nasicus:bug/market-pr …
> Fix & refactor market prices in wallet-list

- src/pages/delegates/delegates.ts
Fixes an issue where you were unable to unvote for a delegate.
Steps to reproduce the issue:
* When you have already voted for a delegate and want to vote for another, you can click on the new delegate and press 'Vote'.
* A modal will pop up stating that you have already voted for a delegate, and if you want to unvote the delegate.
* You can then press 'Unvote', fill in your PIN and a transaction will come up.
* When you send this transaction, you will receive the error that you can only vote for 1 delegate 
This PR solves the issue by making use of the data returned by the modal created in `delegate-details.ts`. That modal returns the actual delegate that we want to vote / unvote in its `dismiss()` function. By using that value in the `delegates.ts` file, we can correctly set the …
> Fix issue with unvoting delegate

- src/pages/contacts/contact-list/contact-list.scss
- src/pages/network-status/network-status.scss
- src/pages/settings/settings.scss
Fixes #92 
The small grey square is due to the scrollviews in Ionic. As far as I was aware, this occurred on the Contacts, Settings and Network Status pages, so I fixed it there by adding `overflow-y: auto;`. Since it seems to be creating "momentum"  on iOS devices, we should have it set to `overflow-y: scroll` in that case. This can be achieved by using `.content-ios` according to [this comment](https://github.com/ionic-team/ionic/issues/6416#issuecomment-338752935), but I don't have an iOS device to properly test this.
> Removes grey square that appears in the corner of some pages

- src/pipes/market-number/market-number.ts
When showing fiat / BTC values in the app, there was a default of 2 and 8 decimals respectively. However, since the value was first changed to the required amount of decimals, and then turned into a Number, the decimals were lost if they ended in a 0. This means that the BTC values were actually shown in 7 decimals instead of 8, and fiat values were sometimes missing decimals (e.g. 4 or 4.1 instead of 4.00 and 4.10)
To fix this, I've changed the MarketNumber pipe to return the value of the toFixed() function instead of changing it to a number (so it now returns a string). As far as I could see, this should not have any adverse effects, as the pipe is only used when displaying information, which doesn't mind the value being a string instead of a number.
> Fixed rounding to always adhere to specified decimals

- src/assets/i18n/en.json
- src/assets/i18n/nl.json
- src/modals/pin-code/pin-code.ts
- src/providers/auth/auth.ts
This PR adds a check for weak PINs when the user wants to create / update one. After a user fills in the 6 digit PIN, it is checked against a list of known weak pins. This is done with an array of values, as a regex is not a good fit for the consecutive digits in increasing / decreasing order, so it is much simpler and easier to understand by defining the weak pins this way. After a weak PIN has been found, the user will be presented with an alert as shown below:
Then the user can decide whether they want to keep the current PIN. When they press 'No', the PIN will be cleared and they can try another. By choosing 'Yes', the user will simply be send to the confirmation screen. This way you don't pressure a user into changing the PIN, but you can give them a little hint that they should …
> Added check for weak pin when creating one

- src/pages/transaction/transaction-send/transaction-send.html
- src/pipes/escape-html/escape-html.ts
- src/pipes/pipes.module.ts
The dropdown containing addresses makes use of [innerHTML] and just shows whatever it is fed, including all kinds of html. This is needed to show the bold text when searching for a contact, but it can also result in unwanted behaviour as shown in the screenshot below:
To counter this, I've added an EscapeHTML pipe that is called first on the address value that is retrieved. Afterwards, the boldprefix pipe is used to ensure that the bold text can still be used to highlight matches (as I assumed that was done in HTML and we don't want to escape that). This results in the following:
> Escape html in address dropdown

- README.md
globally since 8.0.0 came out 2 days ago, there are broken plugins still which break the app otherwise.
npm install -g cordova@7.1.0
> updates readme to ensure devs install the right version of cordova

- src/modals/qr-scanner/qr-scanner.ts
When you try to import a wallet in iOS, if by mistake (or will) you deny the use of the camera, a black box hangs on the screen and can't be removed.
Even if you close the app and reopen it, the box with stay there and you can't use the wallet.
> Fix issue that if you don't allow the camera the app hangs

- src/assets/i18n/en.json
- src/modals/passphrase-word-tester/passphrase-word-tester.html
- src/modals/passphrase-word-tester/passphrase-word-tester.ts
On dev net, when we generate a new wallet and go on the passphrase "word tester" screen to confirm our passphrase, the words are already filled, which is normal.
Just adding here a message to inform that on dev net it's the intended behaviour. (see #116 )
> Dev net: add notice message on passphrase word tester to inform that words are automatically filled

- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/pages/wallet/wallet-dashboard/wallet-dashboard.html
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/pages/wallet/wallet-list/wallet-list.html
- src/providers/contacts-auto-complete/contacts-auto-complete.ts
- src/providers/user-data/user-data.ts
- make wallet labels unique (case insensitive)
- fix bug that wallet label was not updated "on same screen" (problem was that we used the accountLabelPipe with the wallet address, which didn't change and therefore the label stayed the same)
- also don't use pipe if we KNOW we have a wallet => it's unnecessary (+fixes the not update fix)
- fix bug that "address" was returned for wallets when the accountLabelPipe was used (made the "fallback label" useless)
- remove `this.zone.run` statement - don't see a reason to use it there - or did I miss something?
I just wanted to make the wallet label unique, but came on some bugs (maybe even introduced by me in earlier commits) on the way :P
> Make wallet labels unique & fix bugs

- src/pages/wallet/wallet-import/wallet-import.base.ts
- src/providers/user-data/user-data.ts
When we convert watch-only wallet to full wallet, we loose the label we put on the watch-only wallet.
This allows to keep the label.
> Keep label when converting watch-only wallet to full wallet

- src/pages/wallet/wallet-list/wallet-list.html
This PR is basically a (partial) fix / clarification for #103.
The idea is that the 24h change is ONLY for BTC, because only there we can be sure we have the correct data. If we would want to display the change for the fiat currency, we need to call another API or fix it differently, see the other /  closed PR for that.
This is how it looks now:
> Add info that 24h price is for btc

- src/app/app.module.ts
- src/assets/i18n/bg.json
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/gr.json
- src/assets/i18n/it.json
- src/assets/i18n/kor.json
- src/assets/i18n/nl.json
- src/assets/i18n/pt-br.json
- src/assets/i18n/ru.json
- src/assets/i18n/sv.json
- src/models/contact.ts
- src/pages/transaction/transaction-send/transaction-send.html
- src/pages/transaction/transaction-send/transaction-send.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/providers/account-auto-complete/account-auto-complete.ts
- src/providers/user-data/user-data.ts
I found it very annoying that in the "address" field sometimes you only had the address and sometimes only the contact / wallet label.
Plus it wasn't nice that the field jumped around so much (hidden / displayed).
Also you could create a new contact for a wallet instead of just setting a label.
I changed it so it's more consistent for the user and also should be more readable & understandable in code.
Basically there are now 5 possible states in the ui concerning this field:
1. Initial (no address)
2. Existing Contact
3. Wallet with label
4. Wallet without label
5. Unknown (new) address
I made the field disabled for existing contacts & labels.
Todo:
-  [x]  wait until #115 is merged back and use method from there to set label
> Consistent ui behavior in send page

- src/pages/wallet/wallet-import-manual/wallet-import-manual.html
- src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
So here is a 1st version for passphrase word suggestion (#126).
- Suggesting only for last word of passphrase, and only when adding or removing one letter (not acting on copy-pasting words, neither if you want to insert or change a word which is inside the passphrase) : for simplicity and avoiding bugs or bad user experience (I did not want to check / play with cursor position)
- Word suggestion starts from 2 letters (type 'a' => no suggestion, type 'ax' => 'axis' suggested)
- Word suggested are shown in the footer above 'import' button, so they are shown above everything even when keyboard is shown
- Only suggesting in English right now (I will improve on this after, and apply this to bip39 validation too)
I went through a lot of pain to keep the textarea input focused when clicking on …
> Passphrase bip39 word suggestions

- src/assets/i18n/en.json
- src/components/custom-network/custom-network.html
When there is no custom network configured yet, instead of displaying the "classic" UI with messages "Either choose an existing custom network... or create a new custom network",
just display the message "No custom network has been configured yet. Click on the button below to create one."
> Manage custom networks: display a different message when no network has been configured

- src/assets/i18n/en.json
- src/modals/wallet-backup/wallet-backup.ts
- src/models/settings.ts
- src/pages/settings/settings.html
- src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
- src/pages/wallet/wallet-import/wallet-import.base.ts
- src/pages/wallet/wallet-import/wallet-import.ts
- src/providers/settings-data/settings-data.ts
This is a suggestion to allow to generate and import passphrase in any language (from the possible languages defined in bip39 wordlist).
I created a new option "Wordlist language" in Settings : 
The language selected will be used to generate a new wallet (the passphrase will be in this language), and also for importing a wallet from passphrase (we will be able to enter the passphrase in this language).
For wallet import, entering a passphrase in english will still work, even if we select a different language in "Wordlist language". (we might want to generate wallets in a specific language but import a previous wallet which was generated in english)
Please tell me what do you think 😄
> Feature : Generate and import passphrase in all possible bip39 languages

- README.md
It is finally registered yesterday in the Apple App Store formally!
And the download page of ark.io also seems to need a link fix.
> Update apple appstore link

- src/modals/custom-network-create/custom-network-create.ts
- src/providers/ark-api/ark-api.ts
This is as a result of the devnet v2 changes that were made I think. Whenever it sets the network in the API provider, it tries to overwrite the network data with anything stored in the ark-ts config (to make sure it's not out of date). The problem was, any new custom networks had the same "type" as mainnet, meaning all the data for the custom network was overwritten by mainnet data.
> fix: custom networks reset with mainnet on signin

- src/modals/confirm-transaction/confirm-transaction.html
- src/modals/confirm-transaction/confirm-transaction.ts
Disable transaction send button once clicked, to stop strange behaviour of "spamming" a transaction.
> fix: disable tx send button on click

- src/providers/ark-api/ark-api.ts
Skip peer broadcast if can't get peers (this happens when adding a local testnet, for example). It just saves on some messy error pages and poor UX.
> fix: don't broadcast if there are no peers

- src/pages/delegates/delegate-detail/delegate-detail.html
To indicate the precision, displaying 2 decimal digits of approval percentage and productivity.
Many a times, approval displays as '1%'(shown as integer), now it will display as '1.00%'(float)
This shows precision and makes information uniform in every case.
> Always display 2 decimal digit

- package.json
Hides the build progress from from the unit tests, since this will result in a huge output on CircleCI.
> chore: hide test:coverage build progress

- src/pages/delegates/delegate-detail/delegate-detail.html
- src/pages/delegates/delegate-detail/delegate-detail.ts
Firstly, [disabled] was unnecessary as its parent had already used *ngIf.
Next, removed Vote/Unvote Option for Watch-Only Wallets
> Bugfix: remove Vote for Watch-Only

- src/pages/delegates/delegates.html
filterBy pipe of ngx-filter wasn't filtering the list, in the previous version.
Now, used ngFor with ngIf to filter according to searchQuery.username
> Bug: Fix delegate search

- src/pages/wallet/wallet-list/wallet-list.html
Earlier, on loading the profile, if ark balance was zero, it shew 'A 0 $'(didnt show amount in $). This was because on loading profile, fiatCurrency didn't initialize.
Since it is more appropriate not to show the fiat balance when user has 0ark and this also solves the above issue, I have disabled fiat amount when the ark is 0 by using *ngIf directive.
> Disable fiat amount when ARK=0

- src/pages/transaction/transaction-send/transaction-send.ts
This happens when the transaction fails due to network problem, for example.
When createTransactionAndShowConfirm fails, we call hasNotSent to re-enable the send button
> Bug: fix enable send button after failed tx

- src/pages/wallet/wallet-import-manual/wallet-import-manual.html
- src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
On wallet-import-manual page if you press import multiple times you will notice wallet being imported multiple times.
Also, if you do this and aferwards try to remove the wallet, wallet won't be removed properly. It would reappear. It's probably related to #174 .
I was able to reproduce #174 most of the times after importing multiple times. Maybe @rdk1979 , imported multiple times. So most probably this would fix #174 
After import has been pressed, submitted is set to true and import button is hence disabled.
> fix: multiple imports of wallet

- src/pages/wallet/wallet-dashboard/modal/set-label/set-label.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
Should fix #264, by adding a role to the modal dismiss event (which is called on close and submit) as the `onDidDismiss` handler is calling `this.userDataProvider.setWalletLabel()` even if the wallet is only closed.
> fix: save label only when dismissed with 'submit' role

- src/components/amount/amount.ts
transaction_send page allowed users to enter amounts with precision of more than 8 decimal digits. These transactions were failing with status 400 after pressing the send button.
This PR fixes this bug.
Resolves #229 .
> fix: amounts with higher precision

- src/providers/ark-api/ark-api.ts
The `feeStatistics` property has been removed from the endpoint `/node/configuration`, now the endpoint `/node/fees` must be used.
To reduce compatibility issues I just converted the new response to the old model.
> fix: fetch dynamic fees from the new endpoint

- src/models/stored-network.ts
- src/providers/ark-api/ark-api.ts
We refactor the static 51 limit to an activeDelegates limit, which resolves #335.
> refactor: use the activeDelegates number provided by the network

- src/models/profile.ts
- src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
- src/pages/wallet/wallet-list/wallet-list.ts
- src/providers/local-notifications/local-notifications.ts
- src/providers/user-data/user-data.ts
Some async tasks are completed after the user toggles the profile, causing the wallet data to be saved to the wrong profile.
Resolves #337
> fix: update the wallet in the correct profile

- src/pages/delegates/delegates.ts
Use the number of active delegates provided by the network instead of the defined constant. Addition to #336.
> refactor: use activeDelegates provided by network

- src/app/modals/custom-network-edit/custom-network-edit.html
- src/app/pages/transaction/transaction-send/transaction-send.ts
The edit network page is transforming the network version in string.
> fix: ensure numeric type for network version

- src/app/pages/wallet/wallet-list/wallet-list.ts
Reset `wallets` prop to an empty array in case of no profile or empty currentProfile `wallets`
This fixes the case when user deletes the last wallet on his portfolio
> hotfix: Update and propagate wallets property

- angular.json
- karma.conf.js
- src/app/services/storage/storage.spec.ts
It's tests season 🎉 🚀 🥇 
We are gradually adding tests to cover our functionalities, in this PR you'll find:
> test: add storage service unitary tests

- .github/workflows/test.yml
- config.xml
- package-lock.json
- package.json
- src/app/pages/profiles/profile-signin/profile-signin.html
Fix the empty state height on the profile signin page.
> hotfix: release 1.8.1

- .github/workflows/test.yml
- config.xml
- package.json
https://developer.android.com/distribute/best-practices/develop/target-sdk
> chore: bump Android target sdk version to 29

- config.xml
- package.json
- src/app/modals/custom-network-create/custom-network-create.ts
- src/app/modals/custom-network-edit/custom-network-edit.html
- src/app/modals/custom-network-edit/custom-network-edit.ts
- src/app/models/node.ts
- src/app/models/stored-network.ts
- src/app/pages/network/network-status/network-status.html
- src/app/pages/network/network-status/network-status.ts
- src/app/services/ark-api/ark-api.ts
- src/app/utils/ark-client.ts
- src/assets/i18n/en.json
Connect in a default peer for mainnet and devnet, otherwise it looks for a random peer. User will still be able to change the peer in session.
> refactor: use default peer on known networks

- config.xml
- package.json
- src/app/models/transaction.ts
Use the recipient field to sign transactions.
> fix: use recipient address to sign transaction
