src/modals/pin-code/pin-code.html
=> Change elements for pin code buttons

src/assets/i18n/sv.json
Found some minor typos in the Swedish translation.
=> Some typos fixed in Swedish translation

src/app/app.constants.ts, src/assets/i18n/en.json, src/modals/pin-code/pin-code.html, src/modals/pin-code/pin-code.module.ts, src/modals/pin-code/pin-code.ts, src/pipes/pipes.module.ts, src/pipes/seconds-to-time/seconds-to-time.ts, src/providers/auth/auth.ts
Block the user for a period of time after some unsuccessful login attempts.
=> [WIP] Limit on authentication attempts

src/assets/i18n/nl.json
There were some new texts added to the app, for which I've created the Dutch translations.
=> Updated Dutch translation with missing phrases

README.md, TRANSLATING.md
I've added a simple explanation of how one can help translate the app to another language (so which files to edit). This also includes the script that @Nasicus added to check for missing translations, as I believe this is not documented anywhere else.
=> Explanation on how to translate the app

src/assets/i18n/sv.json
Added new translations in Swedish.
ASuyj779EMAf8iLr5QJbbZ7G3JtdaBhq1j
=> Added translations for Swedish

src/modals/confirm-transaction/confirm-transaction.html, src/modals/confirm-transaction/confirm-transaction.scss, src/pages/transaction/transaction-show/transaction-show.html, src/pages/transaction/transaction-show/transaction-show.scss, src/pipes/account-label/account-label.ts, src/pipes/has-account-label/has-account-label.ts, src/pipes/pipes.module.ts
=> Show addresses in detail transaction page

src/pages/contacts/contact-create/contact-create.html, src/pages/contacts/contact-create/contact-create.module.ts, src/pages/contacts/contact-list/contact-list.ts, src/pages/transaction/transaction-send/transaction-send.scss
The contacts list was sorted based on when the contact was added (so first contact that was added at the top). When you have a couple of contacts, I find it easier to look through if they are sorted by name instead of some arbitrary order in which I added them; hence this PR.
Additionally, I also made the button "push up" when the keyboard appears on the "Add Contact" page, so you don't have to first hide the keyboard to see the save button.
=> Sort contacts by name

src/pages/settings/settings.html
=> UI: remove arrow for language and currency in Settings

src/assets/i18n/de.json, src/assets/i18n/en.json, src/components/amount/amount.html, src/components/amount/amount.model.ts, src/components/amount/amount.module.ts, src/components/amount/amount.scss, src/components/amount/amount.ts, src/pages/transaction/transaction-receive/transaction-receive.html, src/pages/transaction/transaction-receive/transaction-receive.module.ts, src/pages/transaction/transaction-receive/transaction-receive.scss, src/pages/transaction/transaction-send/transaction-send.html, src/pages/transaction/transaction-send/transaction-send.module.ts, src/pages/transaction/transaction-send/transaction-send.scss, src/pages/transaction/transaction-send/transaction-send.ts
- make reusable component for amount fields (token / fiat)
- use in receive screen
- same behavior in receive & send screens for the fields (since it's the same component)
This is how it works:
Resovles: #39
=> Add optional amount to receive

src/assets/i18n/en.json, src/assets/i18n/nl.json, src/pages/contacts/contact-list/contact-list.ts
Added the name of the contact on the delete confirmation screen, as it originally only showed "are you sure" and accidentally made me remove the wrong contact 😬
=> Made delete confirmation show contact name

src/assets/i18n/de.json, src/assets/i18n/en.json, src/components/pin-code/pin-code.ts
- also add missing german translations
fixes: #132
=> Show loading screen when updating pin code

src/pages/transaction/transaction-send/transaction-send.ts
The following values will now be set in the send page, if they are present in the scanned qr code:
- `amount` => `amount`
- `vendorField` => `smartBridge`
- `label` => `recipientName` (new contact)
- is only set if there is not already an existing contact / label for this address
Also fixes a bug that `createContact` didn't work anymore ,because the parameters were in the wrong order (once again, my own bug :P)
=> Set qr code values in send page

src/assets/i18n/kor.json
=> updated kor again

src/assets/i18n/en.json, src/modals/custom-network-create/custom-network-create.html, src/modals/custom-network-create/custom-network-create.ts, src/modals/custom-network-edit/custom-network-edit.html, src/modals/custom-network-edit/custom-network-edit.ts, src/providers/ark-api/ark-api.ts
Option to set if network is v2 or not, and do different process if so
=> feat: custom network v2

src/assets/styles/layout.scss
Scrollbar on select options in settings screen
resolves #191
=> feat: scrollbar-language-dialog

src/assets/i18n/fr.json
French translation spelling fixes.
=> French translation spelling fixes.

package.json
Probably fixes #200, needs to be tested.
=> Adds 'cordova-allow-background-audio' package

src/components/custom-network/custom-network.html
=> better ux for button create

src/modals/custom-network-create/custom-network-create.html
=> replace checkbox to toggle

src/assets/i18n/en.json, src/pages/wallet/wallet-dashboard/wallet-dashboard.html, src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
I realized that I do not have the autonomy to update the transactions when I want, so I added the "pull to refresh".
=> Add pull to refresh on wallet dashboard

src/components/amount/amount.ts, src/pages/profiles/profile-signin/profile-signin.module.ts
=> Fixed a few styling errors

package-lock.json, package.json, src/modals/confirm-transaction/confirm-transaction.ts, src/providers/ark-api/ark-api.ts
Fixes error sending transaction.
=> chore: update ark-ts package

config.xml, package.json
=> chore: bump version

config.xml, package-lock.json, package.json, src/providers/ark-api/ark-api.ts
Fixes an issue with mobile app on v2 networks. They were sending transactions to the p2p endpoint, not the public api endpoint.
=> fix: v2 public api transactions

src/pages/transaction/transaction-send/transaction-send.html, src/pages/transaction/transaction-send/transaction-send.ts
This PR is same as #223 . Since I mistakenly deleted the branch that was associated with that PR, we weren't able to make any modifications to the PR.
Anyways, lets come to the PR.
In earlier implementation, 'valid' attribute wasn't defined for any of the number fields as there were no validators of min and max (as pointed by @dated )
In this implementation, no validators have been used. Instead the validForm() has been modified to check for any errors.
Additionally, maxlength of smartbridge string was set to 60 , that is changed to 64.
=> Bugfix: 'transaction-send' page validation

src/pages/wallet/wallet-dashboard/wallet-dashboard.scss
Pull down refresh wasn't worked out for dark mode. Hence, on pulling down to refresh users weren't able to see "refreshing", and cannot even know about this feature (refresh on pull down) when dark mode was enabled.
Added a few attributes to fix those for the dark mode.
=> fix: Refresh not visible in dark mode

src/assets/i18n/en.json
Fixed some grammatical mistakes.
Also replaced 'erroneous' with 'incorrect'. Since the former is not very common.
=> Various Typo/Grammar Fixes

src/assets/i18n/en.json, src/assets/i18n/pt-br.json, src/pages/network-status/network-status.html
adding version in details of peer
=> adding version in details of peer

config.xml, package-lock.json, package.json
I noticed that we never used this package.
=> chore: remove sqlite plugin

src/assets/i18n/fr.json
There was an issue where the french translation for WORDLIST_LANGUAGE was in English, due to there being no translation.
=> fix: add missing settings_page wordlist_language entry

src/pages/profiles/profile-create/profile-create.scss
Added padding to profile name field
=> fix: 'Show Advanced' overlaps text field

src/pages/profiles/profile-create/profile-create.html
=> fix: footer in top when focus input

src/modals/custom-network-create/custom-network-create.ts, src/providers/ark-api/ark-api.ts
Required to add custom networks.
=> fix: debrand p2p config

src/components/confirm-transaction/confirm-transaction.ts, src/models/stored-network.ts, src/models/transaction.ts, src/models/wallet.ts, src/pages/transaction/transaction-response/transaction-response.ts, src/pages/transaction/transaction-show/transaction-show.ts, src/pages/wallet/wallet-dashboard/wallet-dashboard.ts, src/providers/ark-api/ark-api.ts, src/providers/local-notifications/local-notifications.ts, src/providers/user-data/user-data.ts
Fix transaction signing on custom networks.
=> fix: use epoch time provided by network

src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
=> fix: save account balance immediately

package-lock.json, package.json, src/app/app.component.ts, src/app/app.scss, src/assets/i18n/en.json, src/components/input-fee/input-fee.html, src/components/input-fee/input-fee.module.ts, src/components/input-fee/input-fee.scss, src/components/input-fee/input-fee.ts, src/modals/confirm-transaction/confirm-transaction.ts, src/models/stored-network.ts, src/models/transaction.ts, src/pages/delegates/delegate-detail/delegate-detail.html, src/pages/delegates/delegate-detail/delegate-detail.module.ts, src/pages/delegates/delegate-detail/delegate-detail.scss, src/pages/delegates/delegate-detail/delegate-detail.ts, src/pages/delegates/delegates.ts, src/pages/transaction/transaction-send/transaction-send.html, src/pages/transaction/transaction-send/transaction-send.module.ts, src/pages/transaction/transaction-send/transaction-send.ts, src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html, src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.module.ts, src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.ts, src/pages/wallet/wallet-dashboard/wallet-dashboard.ts, src/pipes/units-satoshi/units-satoshi.ts, src/providers/ark-api/ark-api.ts, src/theme/variables.scss, src/utils/ark-utility.ts, test/tsconfig.test.json
=> feat: implement dynamic fee selection for transfer and voting pages

config.xml, package-lock.json, package.json, src/pages/wallet/wallet-import-manual/wallet-import-manual.html
=> chore: bump version to 1.4.0

config.xml, package-lock.json, package.json
=> hotfix: readd sqlite as it's used for backend storage

src/pages/delegates/delegate-detail/delegate-detail.html, src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html
I've moved the form closure on the delegate-registration page, and added a form for voting on the delegate-detail page. Resolves #285 .
=> fix: input-fees to input

src/assets/i18n/sv.json
=> Removed duplicate line 109 in Swedish translation file.

.circleci/config.yml
- Downgrade node 'stable' to 10.
=> fix: change node version to run the tests on CircleCI

config.xml, package.json
=> chore: bump to 1.4.2

src/pages/transaction/transaction-send/transaction-send.ts
=> fix: vendor field max length

src/modals/custom-network-create/custom-network-create.ts, src/pages/transaction/transaction-send/transaction-send.ts
Currently the p2p port is defined.
=>  fix: set the api port to the active peer

src/providers/ark-api/ark-api.ts
This property is set when it finds the delegates, but is not reset.
=> fix: reset the delegates property when switching networks

package-lock.json, package.json, src/providers/ark-api/ark-api.ts
=> fix: remove peer filtering by status

src/assets/i18n/en.json, src/pages/network-status/network-status.html, src/pages/network-status/network-status.ts, src/providers/ark-api/ark-api.ts
Option to reset back to seed peers if struggling to change peers the normal way.
=> feat: peer force reset to seed

src/providers/ark-api/ark-api.ts
The response no longer returns the `errors` field when it was successful.
=> fix: detect successful transactions correctly

src/providers/ark-api/ark-api.ts
Now updates version of seed peer after resetting to it.
=> fix: version on reset peer to seed node

README.md
=> Typo: Fix some punctuation mistakes

config.xml, package.json
=> chore: bump to 1.4.3

package-lock.json, package.json
Use `:4040/config` instead of `:4040`.
=> chore: update ark-ts to change the peer config endpoint

src/components/amount/amount.ts, src/pages/wallet/wallet-dashboard/wallet-dashboard.ts, src/pages/wallet/wallet-list/wallet-list.html, src/providers/ark-api/ark-api.ts
=>  fix: avoid bignumber error when typing decimals

src/pages/wallet/wallet-import-manual/wallet-import-manual.html, src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
=> feat: handle enter key when manually importing wallet

src/pages/transaction/transaction-send/transaction-send.ts
=> fix: set address value after rendering in the transfer page

src/components/pin-code/pin-code.ts, src/pages/transaction/transaction-response/transaction-response.ts
Missing update after migration to v2 api.
=> fix: request second passphrase to sign transactions

config.xml, package.json
=> chore(release): 1.5.1

package.json, src/providers/ark-api/ark-api.ts, yarn.lock
Somehow the stored public key is cleared, breaking the transaction signature.
=> fix: get the public key from passphrase instead of storage

config.xml, package.json
=> chore: bump version to 1.5.2

config.xml, package.json
=> chore: bump version to 1.5.3

src/assets/i18n/zh.json
- TOP WALLETS translation added.
- Delegate translated to 'validator' instead of actual 'delegate'.
=> Fixes in ZH translation

src/providers/ark-api/ark-api.ts, src/utils/ark-peer-discovery.ts, yarn.lock
Update the network even if peer discovery does not find a good seed.
=> fix: fallback when peer discovery fails

src/components/passphrase-input/passphrase-input.ts
Trim passphrase in verification step.
=> fix: trim passphrase in verification step

config.xml, package.json
=> chore: bump version to 1.6.0

config.xml, package-lock.json, package.json
=> fix: remove cordova-plugin-background-mode

src/app/pages/delegates/delegates.html, src/app/pages/wallet/wallet-list/wallet-list.html
- Fix watch-only label in the wallets page
- Fix truncation of delegate approval
=> fix: watch-only and delegate approval labels

src/app/components/input-fee/input-fee.component.html, src/app/pages/transaction/transaction-send/transaction-send.html, src/assets/styles/auto-complete.pcss
- Fix fee label overflow
- Fix input address position
=> fix: fee label overflow and input address position

src/app/components/input-fee/input-fee.component.html, src/app/models/transaction.ts
- Skip amount sent to itself
- Skip amount if not the sender or recipient
=> fix: multipayment additional checks

package-lock.json, src/app/app.component.html, src/app/components/input-fee/input-fee.component.html, src/app/components/input-fee/input-fee.component.ts, src/app/components/input-fee/input-fee.module.ts, src/app/pages/network/network-overview/network-overview.page.html, src/app/pages/network/network-status/network-status.html, src/app/pages/wallet/wallet-list/wallet-list.ts
Unexpected behavior when editing the fee manually.
=> fix: fee and range input correlation

src/app/pages/delegates/delegates.html, src/app/pages/delegates/delegates.pcss
Adapt properties that have been changed in Ionic 5.
=> fix: search bar and segment on the delegates screen

src/app/pages/delegates/delegate-detail/delegate-detail.html, src/app/pages/delegates/delegate-detail/delegate-detail.module.ts, src/app/pages/delegates/delegate-detail/delegate-detail.ts
The input-fee component needs to be wrapped by a form group.
=> fix: delegate vote form

.github/workflows/test.yml, karma.conf.js, package-lock.json, package.json, test/mocks.ts, tsconfig.app.json
https://github.com/kopach/karma-sabarivka-reporter
=> test: fix coverage statistic

ionic.config.json
=> chore: setup ionic appflow

ionic.config.json, package-lock.json, package.json
=> chore: setup ionic appflow sdk

package.json, tsconfig.app.json
Get rid of angular error when compiling modules.
=> build: change target to es5

src/app/app.module.ts
Events like tap and press are not working in the current build.
=> fix: hammerjs with Angular 9

karma.conf.js, src/app/pages/settings/settings.ts, src/app/services/settings-data/settings-data.spec.ts, src/app/services/settings-data/settings-data.ts, src/app/services/storage/storage.spec.ts, src/app/services/storage/storage.ts
Adds `service-data` module unit tests
=> feat: add settings-data unit tests

src/app/components/pin-code/pin-code.ts, src/app/modals/pin-code/pin-code.ts, src/app/pages/intro/intro.ts, src/app/services/auth/auth.spec.ts, src/app/services/auth/auth.ts
Add unit tests for the auth module, we are still missing one `branch` to test an if path where the Bcrypt return an error and researching how to force that result to get 100% of coverage.
=> test: add auth service unit tests

karma.conf.js, src/app/pages/intro/intro.html, src/app/pages/intro/intro.spec.ts, src/app/pages/intro/intro.ts
Refactor to implement the testing library and increase coverage.
=> test: refactor intro page

src/app/components/input-fee/input-fee.component.pcss, src/global.scss
- Reduce horizontal padding
- Remove highlight color from inputs when focused
=> fix: input-fee component tweaks

config.xml, resources/android/xml/network_security_config.xml
Builds compiled by the appflow are receiving "0 unknown error" in http requests.
=> ci: fix connectivity for building in appflow

src/app/services/contacts/contacts.spec.ts, src/app/services/contacts/contacts.ts, src/assets/i18n/en.json, test/mocks.ts
Adds contacts unit tests, updates contacts module to check for an existent contact by name first and updates the mocked class for `UserDataService`.
Still need to think how to cover this private method section and an empty profiles branch 🤔
=> test: add contacts unit tests

.eslintrc.json, package-lock.json, package.json, src/app/app.component.ts, src/app/components/input-currency/input-currency.module.ts, src/app/directives/paste-clipboard-value/paste-clipboard-value.ts, src/app/pages/intro/intro.ts, src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts, src/app/services/ark-api/ark-api.ts, src/app/services/contacts/contacts.ts, src/app/services/user-data/user-data.interface.ts, src/app/services/user-data/user-data.spec.ts, src/app/services/user-data/user-data.ts, test/fixture/networks.fixture.ts, test/fixture/profiles.fixture.ts, test/fixture/wallets.fixture.ts, test/helpers.ts, test/mocks.ts
Add user data service unit tests.
=> test: add user data service specs

.storybook/main.js, .storybook/preview.ts, .storybook/tsconfig.json, karma.conf.js, package-lock.json, package.json, src/app/app.module.ts, src/app/components/input-currency/input-currency.component.ts, src/app/components/input-currency/input-currency.stories.ts, src/app/components/input-fee/input-fee.stories.ts, src/app/components/wallet-picker/wallet-picker.stories.ts
=> feat: add component stories

package-lock.json, src/app/services/address-checker/address-checker.spec.ts, src/app/services/address-checker/address-checker.ts, test/fixture/transactions.fixture.ts, test/fixture/wallets.fixture.ts
Adds address checker unit tests
=> test: add address check unit tests

src/app/app.component.ts
Navigate to the wallets route if press back button on the dashboard screen.
=> fix: back button in the wallet dashboard screen

config.xml, package.json, src/app/pages/wallet/wallet-import-manual/wallet-import-manual.html, src/app/pages/wallet/wallet-import-manual/wallet-import-manual.scss
Fix some styles in the import passphrase screen.
=> fix: import passphrase screen style

config.xml
https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/
=> chore: resolve UIWebView API deprecation

src/assets/i18n/en.json
Capitalize `View Log Report` and `Passphrase Language` items.
=> fix: capitalize translation items

src/app/services/neo-api/neo-api.spec.ts
Cover `neo-api` service module with unit tests
=> feat: add neo-api unit tests

package-lock.json, package.json, src/app/components/bottom-drawer/bottom-drawer.component.spec.ts, src/app/components/bottom-drawer/bottom-drawer.component.ts, src/app/components/bottom-drawer/bottom-drawer.module.ts, src/app/components/bottom-drawer/bottom-drawer.stories.ts, src/app/components/bottom-drawer/bottom-drawer.type.ts, src/app/components/input-address/input-address.spec.ts, src/app/components/wallet-picker/wallet-picker.component.pcss, src/app/components/wallet-picker/wallet-picker.modal.html, src/app/components/wallet-picker/wallet-picker.modal.ts, src/app/pages/transaction/transaction-send/transaction-send.html, src/app/pages/transaction/transaction-send/transaction-send.module.ts, src/app/pages/transaction/transaction-send/transaction-send.ts, src/assets/styles/app.pcss
Add the bottom resizable component.
It is also useful for other components in v2.
=> feat: add bottom drawer component

.github/workflows/test.yml, src/app/services/ark-api/ark-api.spec.ts, src/app/services/ark-api/ark-api.ts, test/fixture/delegates.fixture.ts, test/fixture/transactions-fees.fixture.ts
This aims to cover the ark API service module. Since it's a huge module and should get some refactoring more PR's related to this module could be opened.
=> test: add ark api test cases

src/app/pages/wallet/wallet-dashboard/modal/set-label/set-label.html, src/app/pages/wallet/wallet-dashboard/modal/set-label/set-label.ts, src/app/services/user-data/user-data.ts
There was no option to remove the wallet added previously.
On the set-label page, added an option to remove the label.
And simplified user-data setWalletLabel duplicate label check code.
=> feat: allow removal of wallet label

src/app/components/empty-list/empty-list.html, src/app/pages/profiles/profile-signin/profile-signin.html
Fix the empty state height on the profile signin page.
=> fix: profile signin page height

src/app/auth/shared/auth.controller.ts, src/app/pages/delegates/delegates.ts, src/app/pages/wallet/wallet-list/wallet-list.ts, src/app/settings/settings.component.spec.ts, src/app/settings/settings.component.ts
Subscribe authorization methods to proceed to next events.
=> fix: subscribe auth ctrl methods

config.xml, package-lock.json, package.json
Solves #623 
Add AndroidX support to fix the dex merge classes issue.
=> fix(build): add android x support

.github/workflows/test.yml, src/app/wallets/wallets.component.scss
=> fix: chromedriver version to run e2e job

src/app/services/user-data/user-data.ts
Excludes the given wallet when checking if the label can be updated.
=> fix: exclude current wallet when updating label
